version: "3.7"
services:
  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    image: back:latest
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ./:/app

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
