version: "3.7"
  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
