version: "3.7"
services:
  front:
    image: front:latest
    build:
      context: ./front
      dockerfile: ./Dockerfile
    networks:
      - frontBack
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - "./front:/home/node/app"
      - "/app/node_modules"

  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    image: back:latest
    networks:
      - frontBack
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
    volumes:
      - ./:/app

  postgres-db:
     image: postgres
     volumes:
       - database-data:/var/lib/postgresql/data/project
     environment:
       POSTGRES_PASSWORD: root
       POSTGRES_DB: project
       POSTGRES_USER: root
       PGDATA: /var/lib/postgresql/data/project
     ports:
        - 5432:5432
     networks:
      - frontBack

networks:
  frontBack:
    driver: bridge

volumes:
    database-data: 
